//
// Generated file, do not edit! Created by nedtool 5.7 from floodPacket.msg.
//

#ifndef __FLOODPACKET_M_H
#define __FLOODPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>floodPacket.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet FloodPacket
 * {
 *     int sender;
 *     simtime_t sendingTimeInstace;
 * }
 * </pre>
 */
class FloodPacket : public ::omnetpp::cPacket
{
  protected:
    int sender;
    ::omnetpp::simtime_t sendingTimeInstace;

  private:
    void copy(const FloodPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FloodPacket&);

  public:
    FloodPacket(const char *name=nullptr, short kind=0);
    FloodPacket(const FloodPacket& other);
    virtual ~FloodPacket();
    FloodPacket& operator=(const FloodPacket& other);
    virtual FloodPacket *dup() const override {return new FloodPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSender() const;
    virtual void setSender(int sender);
    virtual ::omnetpp::simtime_t getSendingTimeInstace() const;
    virtual void setSendingTimeInstace(::omnetpp::simtime_t sendingTimeInstace);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FloodPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FloodPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FLOODPACKET_M_H

